plugins {
    id 'java'
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

base {
    archivesName = "${mod_id}-forge-26.x"
}

// Minecraft 26.1.2 requires Java 25.
java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

sourceSets {
    main {
        java {
            srcDir rootProject.file('forge-shared/common/src/main/java')
        }
        resources {
            srcDir project(':core').file('src/main/resources')
        }
        output.resourcesDir = layout.buildDirectory.dir('classes/java/main').get().asFile
    }
}

ext {
    minecraft_version = '26.1.2'
    forge_version = '64.0.8'

    pack_format = 101
    minecraft_version_range = '[26.1.2,26.2)'
    forge_version_range = '[64,)'
    loader_version_range = '[64,)'
}

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run-systemtest')

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
        }

        register('server') {
            args '--nogui'
            jvmArgs '-Djna.tmpdir=./jna'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'
    compileOnly project(':core')
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            pack_format            : pack_format,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(project(':core').sourceSets.main.output)
}

def copyCoreForRun = tasks.register('copyCoreForRun', Copy) {
    dependsOn project(':core').tasks.named('classes')
    from project(':core').sourceSets.main.output.classesDirs
    into layout.buildDirectory.dir('classes/java/main')
}

tasks.withType(JavaExec).configureEach {
    if (name == 'runServer') {
        dependsOn(copyCoreForRun)
        standardInput = System.in
    }
}
